name: watchman
namespace: ""
runtime: quarkus
image: quay.io/ilawson/watchman
imageDigest: ""
trigger: events
builder: quay.io/boson/faas-quarkus-jvm-builder
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
envVars:
  TEST_ENV: 200